name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Set current date as env variable
      run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag jorge2m/chrome-firefox-openjdk17-maven:$NOW
        docker tag jorge2m/chrome-firefox-openjdk17-maven:$NOW jorge2m/chrome-firefox-openjdk17-maven:latest
    - name: Docker Push
      run: |
        docker push jorge2m/chrome-firefox-openjdk17-maven:$NOW
        docker push jorge2m/chrome-firefox-openjdk17-maven:latest
